name: test
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@master
        with:
          go-version: "1.14.7"
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: go test -v -race  -cover -coverprofile=cover.out ./...
